### ISSUE TITLE
explain the first chart

### ISSUE THREAD

**Issue by matthewfdaniels** [the-pudding/anthems#128]
I think the reader might find it helpful to know what they are looking at here. right now, you don't know have any context that this is a project about pitch, so either something referencing the sticky chart of time/hz would be good. a chart title might be all you need!

<img width="371" alt="image" src="https://github.com/the-pudding/anthems/assets/2880174/81512b97-fdac-44ad-bedc-7b8459149ed0">

I also think explaining hz/y-axis would be helpful too.

**Comment by mmcghee18** [comment]
add title
