### ISSUE TITLE
ally check

### ISSUE THREAD

**Issue by mmcghee18** [the-pudding/anthems#99]

**Comment by jadiehm** [comment]
<img width="1398" alt="Screenshot 2024-02-10 at 12 59 08 PM" src="https://github.com/the-pudding/anthems/assets/10521931/17487500-8b82-49a2-a204-30961dfed13c">

need to address focus on faces slider

**Comment by jadiehm** [comment]
review tab progression in slides

**Comment by jadiehm** [comment]
still need to do zoom check
